[package]
name = "seven-zip"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes = "0.8"
byteorder = "1.5"
crc = "3.0"
snafu = "0.7"

[features]
brotli = []

zstd = []
